name: Flatpak (GitHub Pages)
on:
  # Rebuild once a day
  workflow_dispatch:

jobs:
  flatter:
    name: Flatter
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-6.8
      options: --privileged

    strategy:
      matrix:
        arch: [x86_64]
      fail-fast: false
      # Only one job at a time can use the shared repository cache
      max-parallel: 1

    steps:
      # Checkout a repository with Flatpak manifests
      - name: Checkout
        uses: actions/checkout@v3

      # See "GPG Signing" below
      - name: Setup GPG
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Install Flatpak Deps
        run: |
          flatpak install -y app/io.qt.PySide.BaseApp/x86_64/6.8 org.kde.Sdk/x86_64/6.8 org.kde.Platform/x86_64/6.8

      - name: Build
        uses: andyholmes/flatter@main
        with:
          files: io.github.shifterbit.FrayToolsManager.yaml
          arch: ${{ matrix.arch }}
          gpg-sign: ${{ steps.gpg.outputs.fingerprint }}
          upload-bundles: true
          upload-pages-artifact: true
          upload-pages-includes: |
            default.css
            index.html
          flatpak-build-bundle-args: |
            --runtime-repo=https://platform.io/platform.flatpakrepo

  # See "Github Pages" below
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: flatter
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
