name: Flatpak Repo
on:
  # Rebuild once a day
  workflow_dispatch:

jobs:
  flatter:
    name: Flatter
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/andyholmes/flatter/kde:6.7
      options: --privileged

    steps:
      # Checkout a repository with Flatpak manifests
      - name: Checkout
        uses: actions/checkout@v3

      # See "GPG Signing" below
      - name: Setup GPG
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Install Flatpak Deps
        run: |
          flatpak install -y app/io.qt.PySide.BaseApp/x86_64/6.8 org.kde.Sdk/x86_64/6.8 org.kde.Platform/x86_64/6.8

      - name: Build
        uses: andyholmes/flatter@main
        with:
          files: io.github.shifterbit.FrayToolsManager.yaml
          arch: x86_64
          gpg-sign: ${{ steps.gpg.outputs.fingerprint }}
          upload-bundles: false
          upload-pages-artifact: true
          flatpak-build-bundle-args: |
            --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: flatter
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

